name: Run commands on different operating systems
on: [ push ]
jobs:
  ios:
    strategy:
      matrix:
        coin: [monero, wownero]
    name: ios build
    runs-on: macos-14
    steps:
      - name: Checkout monero_c repo
        uses: actions/checkout@v4
        with:
          repository: MrCyjaneK/monero_c
          fetch-depth: 0
          submodules: recursive
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
          limit-access-to-actor: false
      - name: install dependencies
        run: |
          brew install ccache unbound boost@1.76 zmq autoconf automake libtool && brew link boost@1.76
      - name: Patch sources
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "ci@mrcyjanek.net"
          git config --global user.name "CI mrcyjanek.net"
          ./apply_patches.sh ${{ matrix.coin }}
      - name: build
        run: |
          ./build_single.sh ${{ matrix.coin }} host-apple-ios -j$(sysctl -n hw.logicalcpu) 
      - name: rename artifacts
        run: |
          mkdir release/gh/
          for i in release/${{ matrix.coin }}/*
          do
              mv "$i" "release/gh/${{ matrix.coin }}_$(basename $i)"
          done
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/gh/*





























