name: build_all
on: [push]

jobs:
  build_arm64:
    runs-on: buildjet-2vcpu-ubuntu-2204
    strategy:
      fail-fast: false
      matrix:
        os: 
          - debian:sid
          - debian:bookworm
          - debian:bullseye
          - debian:trixie
          - ubuntu:20.04
          - ubuntu:22.04
          - ubuntu:24.04
          - ubuntu:24.10
    container:
      image: ${{ matrix.os }}
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Run Test
        run: |
          uname -a && \
          cat /etc/os-release && \
          printenv          
      - name: Estabilish SSH connection
        run: |
          apt update && \
          (mkdir /root/.ssh || true) && \
          echo "$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa && \
          chmod 600 /root/.ssh/id_rsa && \
          chmod 600 /root/.ssh && \
          ls -lah /root/.ssh/id_rsa && \
          apt install ssh -y && \
          ssh -vvvv -oStrictHostKeyChecking=no waydroid@waydroidrepo.mrcyjanek.net uname -a          
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.os }}
      - name: Install build tools
        run: |
          set -xe && \
          (apt update || true) && \
          apt install -y build-essential cdbs devscripts equivs fakeroot dpkg-dev rsync gnupg wget curl python3-pip git && \
          wget "https://raw.githubusercontent.com/MrCyjaneK/actions-sandbox-for-testing/main/build_apt_repo" -O /bin/build_apt_repo && \
          wget "https://raw.githubusercontent.com/MrCyjaneK/actions-sandbox-for-testing/main/build_changelog" -O /bin/build_changelog && \
          wget "https://raw.githubusercontent.com/MrCyjaneK/actions-sandbox-for-testing/main/build_waydroid_debs" -O /bin/build_waydroid_debs && \
          chmod +x /bin/build_changelog /bin/build_apt_repo /bin/build_waydroid_debs && \
          echo 'deb [trusted=yes] file:/apt/ ./' > /etc/apt/sources.list.d/self.list          
      - name: import GPG key
        run: |
          echo "$APT_GPG" | gpg --import || true          
        env:
          APT_GPG: ${{ secrets.APT_GPG }}
      - name: Build - libglibutil
        run: . /etc/os-release && VERSION_CODENAME=$VERSION_CODENAME build_waydroid_debs libglibutil
      - name: Build - libgbinder
        run: . /etc/os-release && VERSION_CODENAME=$VERSION_CODENAME build_waydroid_debs libgbinder
      - name: Build - gbinder-python
        run: . /etc/os-release && VERSION_CODENAME=$VERSION_CODENAME build_waydroid_debs gbinder-python
      - name: Build - waydroid
        run: . /etc/os-release && VERSION_CODENAME=$VERSION_CODENAME build_waydroid_debs waydroid
      - name: Build - waydroid-sensors (optional)
        run: . /etc/os-release && VERSION_CODENAME=$VERSION_CODENAME build_waydroid_debs waydroid-sensors || true        
      - name: Deploy APT repo
        run: |
          set -xe && \
          cd /apt && \
          . /etc/os-release && \
          PROD_CONF=yes VERSION_CODENAME=$VERSION_CODENAME build_apt_repo && \
          echo "Deploying for: $VERSION_CODENAME" && \
          ls -lah /apt && \
          find /apt -type f && \
          ssh -oStrictHostKeyChecking=no waydroid@waydroidrepo.mrcyjanek.net rm -rf \$HOME/arm64/dists/$VERSION_CODENAME && \
          ssh -oStrictHostKeyChecking=no waydroid@waydroidrepo.mrcyjanek.net mkdir -p \$HOME/arm64/dists/$VERSION_CODENAME && \
          rsync -rPc * waydroid@waydroidrepo.mrcyjanek.net:arm64/dists/$VERSION_CODENAME 
  build_amd64:
    needs: build_arm64
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: 
          - debian:stable
          - debian:oldstable
          - ubuntu:24.04
    container:
      image: ${{ matrix.os }}
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Run Test
        run: |
          uname -a && \
          cat /etc/os-release && \
          printenv          
      - name: Estabilish SSH connection
        run: |
          apt update && \
          (mkdir /root/.ssh || true) && \
          echo "$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa && \
          chmod 600 /root/.ssh/id_rsa && \
          chmod 600 /root/.ssh && \
          ls -lah /root/.ssh/id_rsa && \
          apt install ssh -y && \
          ssh -vvvv -oStrictHostKeyChecking=no waydroid@waydroidrepo.mrcyjanek.net uname -a          
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.os }}
      - name: Install build tools
        run: |
          set -xe && \
          (apt update || true) && \
          apt install -y build-essential cdbs devscripts equivs fakeroot dpkg-dev rsync gnupg wget curl python3-pip git && \
          wget "https://raw.githubusercontent.com/MrCyjaneK/actions-sandbox-for-testing/main/build_apt_repo" -O /bin/build_apt_repo && \
          wget "https://raw.githubusercontent.com/MrCyjaneK/actions-sandbox-for-testing/main/build_changelog" -O /bin/build_changelog && \
          wget "https://raw.githubusercontent.com/MrCyjaneK/actions-sandbox-for-testing/main/build_waydroid_debs" -O /bin/build_waydroid_debs && \
          chmod +x /bin/build_changelog /bin/build_apt_repo /bin/build_waydroid_debs && \
          echo 'deb [trusted=yes] file:/apt/ ./' > /etc/apt/sources.list.d/self.list          
      - name: import GPG key
        run: |
          echo "$APT_GPG" | gpg --import || true          
        env:
          APT_GPG: ${{ secrets.APT_GPG }}
      - name: Build - libglibutil
        run: . /etc/os-release && VERSION_CODENAME=$VERSION_CODENAME build_waydroid_debs libglibutil
      - name: Build - libgbinder
        run: . /etc/os-release && VERSION_CODENAME=$VERSION_CODENAME build_waydroid_debs libgbinder
      - name: Build - gbinder-python
        run: . /etc/os-release && VERSION_CODENAME=$VERSION_CODENAME build_waydroid_debs gbinder-python
      - name: Build - waydroid
        run: . /etc/os-release && VERSION_CODENAME=$VERSION_CODENAME build_waydroid_debs waydroid
      - name: Build - waydroid-sensors (optional)
        run: . /etc/os-release && VERSION_CODENAME=$VERSION_CODENAME build_waydroid_debs waydroid-sensors || true
      - name: Grab arm64 builds
        run: |
          set -xe && \
          cd /tmp && \
          . /etc/os-release && \
          wget -m --no-parent "http://waydroidrepo.mrcyjanek.net/arm64/dists/$VERSION_CODENAME/" && \
          mv $(find /tmp -name '*.deb') /apt && \
          exit 0 || exit 0          
      - name: Deploy APT repo
        run: |
          set -xe && \
          cd /apt && \
          . /etc/os-release && \
          PROD_CONF=yes VERSION_CODENAME=$VERSION_CODENAME build_apt_repo && \
          echo "Deploying for: $VERSION_CODENAME" && \
          ls -lah /apt && \
          find /apt -type f && \
          ssh -oStrictHostKeyChecking=no waydroid@waydroidrepo.mrcyjanek.net rm -rf \$HOME/amd64/dists/$VERSION_CODENAME && \
          ssh -oStrictHostKeyChecking=no waydroid@waydroidrepo.mrcyjanek.net mkdir -p \$HOME/amd64/dists/$VERSION_CODENAME && \
          rsync -rPc * waydroid@waydroidrepo.mrcyjanek.net:amd64/dists/$VERSION_CODENAME 