name: Run commands on different operating systems
on: [ push ]
jobs:
  windows:
    strategy:
      matrix:
        coin: [COIN_MONERO, COIN_WOWNERO]
        stealth: [LIBSTEALTH_DISABLED]
    name: windows build
    runs-on: windows-latest
    steps:
      - name: Checkout unnamed_monero_wallet repo
        uses: actions/checkout@v4
        with:
          repository: MrCyjaneK/unnamed_monero_wallet
          fetch-depth: 0
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git make xz mingw-w64-x86_64-gcc
      - name: Codegen
        run: ./codegen.sh -D${{ matrix.coin }} -D${{ matrix.stealth }}
        shell: msys2 {0}
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
      - name: Flutter pub get
        run: |
          flutter pub get
      - name: ./build_changelog.sh [dummy]
        run: dart run flutter_oss_licenses:generate -o lib/helpers/licenses.g.dart
      - name: make version
        run: make version
        shell: msys2 {0}
      - name: build
        run: |
          flutter build windows -v
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false





















